spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:5432/postgres
    username: postgres.jkkwbevrahufvjpcxxsp
    password: foliom4n@123
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      pool-name: supabaseds
      connection-timeout: 30000     # 30 seconds
      idle-timeout: 600000          # 10 minutes
      max-lifetime: 1800000         # 30 minutes
